use reqwest::{Client, Url};
use serde::{Deserialize, Serialize};
use tracing::{debug, info, instrument};

#[instrument(skip(http_client))]
pub async fn get_salmon_log(http_client: Client, username: &str) -> LogList {
    let statink_salmon_api_url = Url::parse(&format!("https://stat.ink/@{username}/salmon3.json"))
        .expect("Unable to create stat.ink Salmon URL");
    debug!("Fetching Salmon log ({statink_salmon_api_url})");

    let salmon_log_request = http_client
        .get(statink_salmon_api_url)
        .send()
        .await
        .expect("Unable to fetch Salmon Log");
    debug!("Transforming Salmon logs to JSON...");

    let out = salmon_log_request
        .json::<LogList>()
        .await
        .expect("Unable to parse Salmon Log");
    debug!("Done!");

    out
}

#[instrument(skip(http_client, link))]
pub async fn add_link_to_salmon_log(http_client: Client, log_uuid: &str, link: &str) {
    let endpoint_url = Url::parse_with_params(
        "https://stat.ink/api/internal/patch-salmon3-url",
        &[("id", log_uuid)],
    )
    .unwrap();

    debug!("Updating Salmon log");
    let update_request = http_client
        .post(endpoint_url)
        .form(&[("_method", "PATCH"), ("link_url", link)])
        .send()
        .await;

    update_request.expect("Unable to update Salmon log!");
    info!("Updated Salmon log!");
}

// Code below generated by https://app.quicktype.io
// Example code that deserializes and serializes the model.
// extern crate serde;
// #[macro_use]
// extern crate serde_derive;
// extern crate serde_json;
//
// use generated_module::SalmonLog;
//
// fn main() {
//     let json = r#"{"answer": 42}"#;
//     let model: SalmonLog = serde_json::from_str(&json).unwrap();
// }

pub type LogList = Vec<Log>;

#[allow(clippy::struct_excessive_bools)]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Log {
    pub id: String,
    pub url: String,
    pub uuid: String,
    pub private: bool,
    pub big_run: bool,
    pub start_at: Time,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Time {
    pub time: i64,
    pub iso8601: String,
}
